apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
labels:
    gitops-test: autosync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: orders-api-sa
      containers:
        - name: orders-api
          image: acrordersdev001.azurecr.io/enterprise-orders-api:4429a4b065af374bf9f726c29bb12db52b530a58
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: orders-api-service
spec:
  selector:
    app: orders-api
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP