apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift
  labels:
    app: hello-openshift

spec:
  replicas: 3

  selector:
    matchLabels:
      app: hello-openshift

  template:
    metadata:
      labels:
        app: hello-openshift

    spec:
      serviceAccountName: hello-sa

      containers:
        - name: nginx-unprivileged
          image: nginxinc/nginx-unprivileged:latest
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - name: http
              containerPort: 8080

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: hello-config
                  key: APP_NAME

            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: hello-config
                  key: ENVIRONMENT

            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: API_USERNAME

            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: API_PASSWORD