apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-openshift

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-openshift

  minReplicas: 2
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50