apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding

subjects:
  - kind: ServiceAccount
    name: hello-sa
    namespace: wislooten-1-dev

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader